export const typeStyles: Record<string, { bgColor: string; color: string }> = {
  normal: { bgColor: "#A8A878", color: "#fff" },
  fire: { bgColor: "#F08030", color: "#fff" },
  water: { bgColor: "#6890F0", color: "#fff" },
  electric: { bgColor: "#F8D030", color: "#000" },
  grass: { bgColor: "#78C850", color: "#fff" },
  ice: { bgColor: "#98D8D8", color: "#000" },
  fighting: { bgColor: "#C03028", color: "#fff" },
  poison: { bgColor: "#A040A0", color: "#fff" },
  ground: { bgColor: "#E0C068", color: "#000" },
  flying: { bgColor: "#A890F0", color: "#fff" },
  psychic: { bgColor: "#F85888", color: "#fff" },
  bug: { bgColor: "#A8B820", color: "#fff" },
  rock: { bgColor: "#B8A038", color: "#fff" },
  ghost: { bgColor: "#705898", color: "#fff" },
  dragon: { bgColor: "#7038F8", color: "#fff" },
  dark: { bgColor: "#705848", color: "#fff" },
  steel: { bgColor: "#B8B8D0", color: "#000" },
  fairy: { bgColor: "#EE99AC", color: "#000" },
};
